#! /bin/bash

rm -rf rootfs_AMD64
mkdir rootfs_AMD64
cd rootfs_AMD64
cp -r -t . ../../live-bootstrap/seed/stage0-posix/*
cd ..
strace -f -o trace_AMD64.txt -e trace=open,openat,close,chmod,chdir,dup,fcntl,link,linkat,unlink,fork,execve chroot rootfs_AMD64 /bootstrap-seeds/POSIX/AMD64/kaem-optional-seed
